### ISSUE TITLE
Main Menu Crash: ConcurrentModificationException on Asynchronously building [color] search tree

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/HadEnoughItems#16]
Game crashes as soon as main menu should be shown.  
`Vanilla Fix` mod handle the crash, so i still could play.

Crash stack trace:
```less
java.util.ConcurrentModificationException: null
	at java.util.WeakHashMap$HashIterator.remove(WeakHashMap.java:821) ~[?:1.8.0_51]
	at zone.rong.loliasm.client.sprite.FramesTextureData.onClientTick(FramesTextureData.java:34) ~[FramesTextureData.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3440_FramesTextureData_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
```

Considering stack trace pointing to `loliasm`, this fatal happens right after this line, so i though HEI is actual issue reason:
```less
[pool-13-thread-1/INFO] [HadEnoughItems]: Asynchronously building [color] search tree...
```

I tried to reload game and got same crash at exact same place.

**Comment by Rongmario** [comment]
Fixed in dev: https://github.com/LoliKingdom/LoliASM/issues/84
