### ISSUE TITLE
Probabilistic Crash

### ISSUE THREAD

**Issue by IAmNotGEM** [CleanroomMC/HadEnoughItems#41]
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Had Enough Items (jei)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 851
    at me.towdium.pinin.fastutil.chars.Char2ObjectOpenHashMap.get(Char2ObjectOpenHashMap.java:348)
    at me.towdium.pinin.searchers.TreeSearcher$NAcc.lambda$null$0(TreeSearcher.java:261)
    at me.towdium.pinin.utils.IndexSet.foreach(IndexSet.java:51)
    at me.towdium.pinin.searchers.TreeSearcher$NAcc.lambda$null$1(TreeSearcher.java:261)
    at me.towdium.pinin.fastutil.chars.CharIterable.forEach(CharIterable.java:74)
    at me.towdium.pinin.searchers.TreeSearcher$NAcc.lambda$get$2(TreeSearcher.java:260)
    at java.util.Map.forEach(Unknown Source)
    at me.towdium.pinin.searchers.TreeSearcher$NAcc.get(TreeSearcher.java:258)
    at me.towdium.pinin.searchers.TreeSearcher.search(TreeSearcher.java:62)
    at me.towdium.hecharacters.util.Match$FakeTree.getSearchResults(Match.java:120)
    at mezz.jei.search.PrefixedSearchable.getSearchResults(PrefixedSearchable.java:86)
    at mezz.jei.search.CombinedSearchables.getSearchResults(CombinedSearchables.java:17)
    at mezz.jei.search.ElementSearch.getSearchResults(ElementSearch.java:57)
    at mezz.jei.ingredients.IngredientFilter.findMatchingElements(IngredientFilter.java:81)
    at mezz.jei.ingredients.IngredientRegistry.isIngredientVisible(IngredientRegistry.java:382)
    at mezz.jei.recipes.RecipeRegistry.getRecipeCatalysts(RecipeRegistry.java:655)
    at mezz.jei.recipes.RecipeRegistry.isCategoryVisible(RecipeRegistry.java:382)
    at mezz.jei.recipes.RecipeRegistry.getRecipeCategories(RecipeRegistry.java:368)
    at mezz.jei.gui.recipes.RecipeGuiLogic.<init>(RecipeGuiLogic.java:43)
    at mezz.jei.gui.recipes.RecipesGui.<init>(RecipesGui.java:86)
    at mezz.jei.startup.JeiStarter.start(JeiStarter.java:107)
    at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
    at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:757)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4601)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Rongmario** [comment]
Could be a https://github.com/CleanroomMC/HadEnoughCharacters bug instead. What do you think @vfyjxf?

**Comment by vfyjxf** [comment]
emm, let me check what changes hei made that caused the problem.
