### ISSUE TITLE
Crash on startup w. The Betweenlands v3.9.5

### ISSUE THREAD

**Issue by Shazuli** [CleanroomMC/HadEnoughItems#50]
With [The Betweenlands](https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod) version [3.9.5](https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod/files/4359749) (and presumably above) installed with HEI causes the game to crash on startup.

<details>
  <summary>crash-2023-03-05_15.39.01-client.txt</summary>

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.5-core.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 3/5/23 3:39 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
Caused by: java.util.ConcurrentModificationException
	at java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:806)
	at java.util.WeakHashMap$KeyIterator.next(WeakHashMap.java:839)
	at net.minecraft.item.crafting.Ingredient.invalidateAll(Ingredient.java:103)
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:587)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:916)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:259)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 6.1.12-1-MANJARO
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2460391336 bytes (2346 MB) / 3978297344 bytes (3794 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 2 total; -Xms2048m -Xmx8064m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID              | Version      | Source                                  | Signature                                |
	|:------- |:--------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA  | minecraft       | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA  | mcp             | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA  | FML             | 8.0.99.99    | forge-1.12.2-14.23.5.2859-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJAE | forge           | 14.23.5.2859 | forge-1.12.2-14.23.5.2859-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA  | jei             | 4.24.0       | HadEnoughItems_1.12.2-4.24.0.jar        | None                                     |
	| LCHIJA  | thebetweenlands | 3.9.5        | TheBetweenlands-3.9.5-universal.jar     | 38067d6878811efb38b6a045521cfd80b9b60b38 |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.9.5-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 470.161.03' Renderer: 'NVIDIA GeForce GTX 660/PCIe/SSE2'
```

**Comment by Shazuli** [comment]
I might mention that just using JEI ([v4.16.1.1001](https://www.curseforge.com/minecraft/mc-mods/jei/files/4393461)) works fine.

**Comment by sddsd2332** [comment]
Refer to this https://github.com/Angry-Pixel/The-Betweenlands/issues/1350#issuecomment-1386901637
