### ISSUE TITLE
Bug: JER Villagers tab not working (`Just Enough Resources` compat)

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/HadEnoughItems#65]
Opening *Villagers* tab when JER installed caused error spam and malfunction of tab itself.

How to reproduce:
1. Install only `HEI 4.25.0` + `JER 0.9.3.203`
2. Run game
3. Open JEI tab with villagers
4. See how total numbers of pages in this trade becomes less and less
5. After some scrolling, only 2 bugged trades left

https://github.com/CleanroomMC/HadEnoughItems/assets/936618/cf12b4ee-83cc-463a-bb3a-8a94fa864617

```less
[Client thread/ERROR] [HadEnoughItems]: Error caught from Recipe Category: jeresources.jei.villager.VillagerCategory
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555) ~[?:1.8.0_352]
	at java.util.LinkedList.get(LinkedList.java:476) ~[?:1.8.0_352]
	at jeresources.entry.VillagerEntry.getVillagerTrades(VillagerEntry.java:37) ~[VillagerEntry.class:?]
	at jeresources.jei.villager.VillagerWrapper.getTrades(VillagerWrapper.java:35) ~[VillagerWrapper.class:?]
	at jeresources.jei.villager.VillagerCategory.setRecipe(VillagerCategory.java:58) ~[VillagerCategory.class:?]
	at jeresources.jei.villager.VillagerCategory.setRecipe(VillagerCategory.java:16) ~[VillagerCategory.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:69) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:198) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:492) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:538) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.nextPage(RecipeGuiLogic.java:254) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_146284_a(RecipesGui.java:438) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443) [blk.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73864_a(RecipesGui.java:336) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) [blk.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_146274_d(RecipesGui.java:304) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) [blk.class:?]
```

[debug.log](https://github.com/CleanroomMC/HadEnoughItems/files/12817907/debug.log)

**Comment by Krutoy242** [comment]
Rolling back to `JustEnoughResources-1.12.2-0.9.2.60` fixed the issue. Seems like i should address it to JER github instead.

https://github.com/way2muchnoise/JustEnoughResources/issues/423

**Comment by magcicada** [comment]
The weird that when running JER with HEI, the int of `level` 
https://github.com/way2muchnoise/JustEnoughResources/blob/4daa2e0284075ce87546ce3668b14c895b800b58/src/main/java/jeresources/entry/VillagerEntry.java#L37 here will get int +1 than the original int of `level`, so it will get `IndexOutOfBoundsException`.

**Comment by Krutoy242** [comment]
> The weird that when running JER with HEI, the int of `level` [way2muchnoise/JustEnoughResources@`4daa2e0`/src/main/java/jeresources/entry/VillagerEntry.java#L37](https://github.com/way2muchnoise/JustEnoughResources/blob/4daa2e0284075ce87546ce3668b14c895b800b58/src/main/java/jeresources/entry/VillagerEntry.java#L37) here will get int +1 than the original int of `level`, so it will get `IndexOutOfBoundsException`.

As far as i understand, even JEI would have this error, not just HEI.

**Comment by magcicada** [comment]
[JustEnoughResources-1.12.2-0.9.3.jar.zip](https://github.com/CleanroomMC/HadEnoughItems/files/12906187/JustEnoughResources-1.12.2-0.9.3.jar.zip)
try this mod file

**Comment by magcicada** [comment]
![image](https://github.com/CleanroomMC/HadEnoughItems/assets/45464670/f8b81427-b014-4ca3-aae2-2807c2fd2ab4)
maybe it has been fixed
